using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("PFSystemObjects")]
[assembly: AssemblyDescription("System Objects for ProFast Windows Applications")]
[assembly: AssemblyConfiguration(".NET 4.0")]
[assembly: AssemblyCompany("ProFast Computing")]
[assembly: AssemblyProduct("PFSystemObjects for Windows Apps")]
[assembly: AssemblyCopyright("Copyright © Microsoft 2012-2015")]
[assembly: AssemblyTrademark("PFApps")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
//new guid created 10/14/2012
//new guid was generated by VS when new class project created
[assembly: Guid("3f811039-1076-42b3-92d4-c132689309ce")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("3.0.*")]
[assembly: AssemblyFileVersion("1.0.0.0")]
